# Generated by Django 2.2 on 2020-05-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Мобильный телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_photo', verbose_name='Фото')),
                ('type', models.CharField(choices=[('client', 'Физическое лицо'), ('company', 'Юридическое лицо')], default='Null', max_length=20, verbose_name='Тип')),
                ('birth_date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('man', 'Мужской'), ('woman', 'Женский')], default='Null', max_length=20, null=True, verbose_name='Тип')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН')),
                ('okpo', models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Телефон контактного лица')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
