# Generated by Django 2.2 on 2020-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200505_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Bishkek', 'Бишкек')], default='Bishkek', max_length=20, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('entrance_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('flat_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер квартиры/офиса')),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
    ]
